// Copyright (C) 2020, RTE (http://www.rte-france.com)
// Copyright (C) 2023-2025 Savoir-faire Linux, Inc.
// SPDX-License-Identifier: CC-BY-4.0

= Repository manifest

This repository contains an XML manifest for `repo`, the multiple git repository
tool.

== Using repo to checkout your system code

The following commands will allow you to checkout a working set of repositories
to build the system:

```
# Use a work directory for your project
mkdir seapath
cd seapath/
```

Next checkout repositories using the repo-manifest:

```
repo init -u "https://github.com/seapath/repo-manifest.git"
repo sync
```

To checkout the dunfell version:

```
repo init -u "https://github.com/seapath/repo-manifest.git" -m dunfell.xml
repo sync
```

To checkout the v1.0.0 version:

```
repo init -u "https://github.com/seapath/repo-manifest.git" -m v1.0.0.xml
repo sync
```

The system's repositories will then be checked out in the current directory at
the paths and revisions expressed in the xml file.

== Why repo ?

The system we are building is split into several Git repositories, each of them
containing a specific set of files for a specific function.

To work together well, these repositories must be checked out at a very specific
revision, which is compatible with each other's repository specific revision.
This can be a tedious task to do and require manual repetition, and
that's where `repo` comes in handy.

== Installing repo on your system

The `repo` tool can be installed on Linux using your distro's package manager:

On Debian/Ubuntu systems, use the following command:

```
sudo apt install repo
```

For other systems, the homepage of the project is at
https://gerrit.googlesource.com/git-repo/
